### ISSUE TITLE
Are there some build in function for camelCasing the results

### ISSUE THREAD

**Issue by larserikfinholt** [ShareCoffee/ShareCoffee#47]
First, thanks for a great library!

It would be great if we could have a setting that would camelcase property names when fetching list items.(or maybe there already is? - could not find)

Larsi

**Comment by ThorstenHans** [comment]
You mean the listItem properties?

like myListItem.title instead of myListItem.Title? If that's what you're looking for, I'm not sure if it will make sense. I know that it's a kind of ugly to have properties starting with capital letters in JS. But applying a function to each and every object which will be processed may increase the number of JS ops dramatically.

you can of course easily pipe all the results through a method like this

http://jsfiddle.net/22j96zkf/

in order to get camel-cased properties.

**Comment by larserikfinholt** [comment]
I see. Thanks for the method,  I'll just use that if can't get used to the
uppercase.
26. sep. 2014 17:52 skrev "Thorsten Hans" notifications@github.com
følgende:

**Comment by ThorstenHans** [comment]
Yeah. In the end it's up to you, just pipe all the results within the success callback to the method and objects will provide both kinds of properties as shown in the jsfiddle.
